//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorDrawing_WinForm_.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VectorDrawing_WinForm_.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string grbx_color {
            get {
                return ResourceManager.GetString("grbx_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string grbx_coord {
            get {
                return ResourceManager.GetString("grbx_coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string grbx_type {
            get {
                return ResourceManager.GetString("grbx_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string grbx_width {
            get {
                return ResourceManager.GetString("grbx_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas 1.
        /// </summary>
        internal static string tbpg_1 {
            get {
                return ResourceManager.GetString("tbpg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas 2.
        /// </summary>
        internal static string tbpg_2 {
            get {
                return ResourceManager.GetString("tbpg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tsmi_about {
            get {
                return ResourceManager.GetString("tsmi_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string tsmi_color {
            get {
                return ResourceManager.GetString("tsmi_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tsmi_exit {
            get {
                return ResourceManager.GetString("tsmi_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string tsmi_file {
            get {
                return ResourceManager.GetString("tsmi_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string tsmi_lang {
            get {
                return ResourceManager.GetString("tsmi_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string tsmi_lineWidth {
            get {
                return ResourceManager.GetString("tsmi_lineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string tsmi_open {
            get {
                return ResourceManager.GetString("tsmi_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string tsmi_save {
            get {
                return ResourceManager.GetString("tsmi_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tsmi_settings {
            get {
                return ResourceManager.GetString("tsmi_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string tsmi_style {
            get {
                return ResourceManager.GetString("tsmi_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string tsmi_tabs {
            get {
                return ResourceManager.GetString("tsmi_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tsmi_type {
            get {
                return ResourceManager.GetString("tsmi_type", resourceCulture);
            }
        }
    }
}
